name: nexustools
description: Installer for ADB, Fastboot, and other Android tools.
version: 5.0.0
homepage: https://github.com/corbindavenport/nexus-tools/

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  http:
  io:
  uuid:
  archive: ^3.2.2
  console: